{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "2652b167-66eb-4a22-b4da-9690c784e474",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Azhar Computer\\AppData\\Local\\Temp\\ipykernel_12092\\2761462656.py:221: UserWarning: The parameters have been moved from the Blocks constructor to the launch() method in Gradio 6.0: theme. Please pass these parameters to launch() instead.\n",
      "  with gr.Blocks(theme=gr.themes.Soft()) as app:\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "* Running on local URL:  http://127.0.0.1:7862\n",
      "* Running on public URL: https://6dd9ad4506dd8d9d6b.gradio.live\n",
      "\n",
      "This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div><iframe src=\"https://6dd9ad4506dd8d9d6b.gradio.live\" width=\"100%\" height=\"500\" allow=\"autoplay; camera; microphone; clipboard-read; clipboard-write;\" frameborder=\"0\" allowfullscreen></iframe></div>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/plain": []
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import gradio as gr\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import os\n",
    "import zipfile\n",
    "\n",
    "sns.set_theme(style=\"whitegrid\", palette=\"pastel\")\n",
    "\n",
    "# =========================\n",
    "# LOAD DATA\n",
    "# =========================\n",
    "\n",
    "df = pd.read_csv(\n",
    "    r\"D:\\EDA 4th\\dashboard_project\\data\\Traffic_Collision_Data_from_2010_to_Present (2).csv\"\n",
    ")\n",
    "\n",
    "df = df.drop_duplicates()\n",
    "df.columns = df.columns.str.strip()\n",
    "\n",
    "# =========================\n",
    "# DATE HANDLING\n",
    "# =========================\n",
    "\n",
    "if \"Date Occurred\" in df.columns:\n",
    "    df[\"Date Occurred\"] = pd.to_datetime(df[\"Date Occurred\"], errors=\"coerce\")\n",
    "    df = df[df[\"Date Occurred\"].notna()]\n",
    "    df[\"Year\"] = df[\"Date Occurred\"].dt.year\n",
    "    df[\"Month\"] = df[\"Date Occurred\"].dt.month\n",
    "\n",
    "# =========================\n",
    "# CLEANING\n",
    "# =========================\n",
    "\n",
    "for col in df.columns:\n",
    "    if df[col].dtype == \"object\":\n",
    "        df[col] = df[col].fillna(\"Unknown\")\n",
    "    else:\n",
    "        df[col] = df[col].fillna(df[col].median())\n",
    "\n",
    "# =========================\n",
    "# AREA COLUMN\n",
    "# =========================\n",
    "\n",
    "area_col = None\n",
    "for c in df.columns:\n",
    "    if \"AREA\" in c.upper():\n",
    "        area_col = c\n",
    "        break\n",
    "\n",
    "areas = sorted(df[area_col].dropna().unique().tolist()) if area_col else []\n",
    "\n",
    "# =========================\n",
    "# SAVE ZIP FUNCTION\n",
    "# =========================\n",
    "\n",
    "def save_zip(*figs):\n",
    "    os.makedirs(\"charts\", exist_ok=True)\n",
    "\n",
    "    paths = []\n",
    "\n",
    "    for i, fig in enumerate(figs, start=1):\n",
    "        path = f\"charts/chart_{i}.png\"\n",
    "        fig.savefig(path, bbox_inches=\"tight\")\n",
    "        paths.append(path)\n",
    "\n",
    "    zip_path = \"charts/all_charts.zip\"\n",
    "\n",
    "    with zipfile.ZipFile(zip_path, \"w\") as z:\n",
    "        for p in paths:\n",
    "            z.write(p)\n",
    "\n",
    "    return zip_path\n",
    "\n",
    "# =========================\n",
    "# DASHBOARD FUNCTION\n",
    "# =========================\n",
    "\n",
    "def dashboard(start_date, end_date, categories, max_age, search_text):\n",
    "\n",
    "    temp = df.copy()\n",
    "\n",
    "    # DATE FILTER\n",
    "    if \"Date Occurred\" in temp.columns:\n",
    "        temp[\"Date Occurred\"] = pd.to_datetime(temp[\"Date Occurred\"], errors=\"coerce\")\n",
    "\n",
    "        if start_date:\n",
    "            temp = temp[temp[\"Date Occurred\"] >= pd.to_datetime(start_date, errors=\"coerce\")]\n",
    "\n",
    "        if end_date:\n",
    "            temp = temp[temp[\"Date Occurred\"] <= pd.to_datetime(end_date, errors=\"coerce\")]\n",
    "\n",
    "    # CATEGORY FILTER\n",
    "    if area_col and categories:\n",
    "        temp = temp[temp[area_col].isin(categories)]\n",
    "\n",
    "    # AGE FILTER\n",
    "    if \"Victim Age\" in temp.columns:\n",
    "        temp = temp[temp[\"Victim Age\"].notna()]\n",
    "        temp = temp[temp[\"Victim Age\"] <= max_age]\n",
    "\n",
    "    # SEARCH FILTER\n",
    "    if search_text:\n",
    "        temp = temp[\n",
    "            temp.astype(str).apply(\n",
    "                lambda x: x.str.contains(search_text, case=False, na=False)\n",
    "            ).any(axis=1)\n",
    "        ]\n",
    "\n",
    "    # =========================\n",
    "    # KPI\n",
    "    # =========================\n",
    "\n",
    "    total = len(temp)\n",
    "    avg_age = round(temp[\"Victim Age\"].mean(), 2) if \"Victim Age\" in temp.columns else 0\n",
    "\n",
    "    # =========================\n",
    "    # 1 PIE CHART (FIXED)\n",
    "    # =========================\n",
    "\n",
    "    fig1, ax1 = plt.subplots()\n",
    "    if \"Victim Sex\" in temp.columns:\n",
    "        pie_data = temp[\"Victim Sex\"].replace(\"Unknown\", pd.NA).dropna()\n",
    "        if len(pie_data) > 0:\n",
    "            pie_data.value_counts().plot.pie(\n",
    "                autopct=\"%1.1f%%\",\n",
    "                ax=ax1\n",
    "            )\n",
    "    ax1.set_title(\"Gender Distribution\")\n",
    "\n",
    "    # =========================\n",
    "    # 2 COUNT PLOT (FIXED)\n",
    "    # =========================\n",
    "\n",
    "    fig2, ax2 = plt.subplots()\n",
    "    if \"Victim Sex\" in temp.columns:\n",
    "        count_data = temp[\"Victim Sex\"].replace(\"Unknown\", pd.NA).dropna()\n",
    "        if len(count_data) > 0:\n",
    "            order = count_data.value_counts().index\n",
    "            sns.countplot(x=count_data, order=order, ax=ax2)\n",
    "    ax2.set_title(\"Count Plot\")\n",
    "\n",
    "    # =========================\n",
    "    # 3 VIOLIN PLOT (FIXED)\n",
    "    # =========================\n",
    "\n",
    "    fig3, ax3 = plt.subplots()\n",
    "    if \"Victim Sex\" in temp.columns and \"Victim Age\" in temp.columns:\n",
    "        clean = temp[[\"Victim Sex\", \"Victim Age\"]].dropna()\n",
    "        clean = clean[clean[\"Victim Sex\"] != \"Unknown\"]\n",
    "        if len(clean) > 0:\n",
    "            sns.violinplot(x=\"Victim Sex\", y=\"Victim Age\", data=clean, ax=ax3)\n",
    "    ax3.set_title(\"Violin Plot\")\n",
    "\n",
    "    # =========================\n",
    "    # 4 HISTOGRAM\n",
    "    # =========================\n",
    "\n",
    "    fig4, ax4 = plt.subplots()\n",
    "    if \"Victim Age\" in temp.columns:\n",
    "        ax4.hist(temp[\"Victim Age\"].dropna(), bins=25)\n",
    "    ax4.set_title(\"Age Distribution\")\n",
    "\n",
    "    # =========================\n",
    "    # 5 BAR CHART\n",
    "    # =========================\n",
    "\n",
    "    fig5, ax5 = plt.subplots()\n",
    "    if area_col:\n",
    "        temp[area_col].value_counts().head(10).plot(kind=\"bar\", ax=ax5)\n",
    "    ax5.set_title(\"Top Areas\")\n",
    "\n",
    "    # =========================\n",
    "    # 6 LINE CHART\n",
    "    # =========================\n",
    "\n",
    "    fig6, ax6 = plt.subplots()\n",
    "    if \"Year\" in temp.columns:\n",
    "        temp.groupby(\"Year\").size().plot(ax=ax6)\n",
    "    ax6.set_title(\"Year Trend\")\n",
    "\n",
    "    # =========================\n",
    "    # 7 SCATTER (SAFE FIX)\n",
    "    # =========================\n",
    "\n",
    "    fig7, ax7 = plt.subplots()\n",
    "    lat_col = None\n",
    "    for c in temp.columns:\n",
    "        if \"LAT\" in c.upper():\n",
    "            lat_col = c\n",
    "            break\n",
    "\n",
    "    if \"Victim Age\" in temp.columns and lat_col:\n",
    "        clean = temp[[lat_col, \"Victim Age\"]].dropna()\n",
    "        if len(clean) > 0:\n",
    "            ax7.scatter(clean[\"Victim Age\"], clean[lat_col])\n",
    "    ax7.set_title(\"Scatter Plot\")\n",
    "\n",
    "    # =========================\n",
    "    # 8 HEATMAP\n",
    "    # =========================\n",
    "\n",
    "    fig8, ax8 = plt.subplots()\n",
    "    numeric = temp.select_dtypes(include=[\"int64\", \"float64\"])\n",
    "    if not numeric.empty:\n",
    "        sns.heatmap(numeric.corr(), cmap=\"coolwarm\", ax=ax8)\n",
    "    ax8.set_title(\"Heatmap\")\n",
    "\n",
    "    # =========================\n",
    "    # ZIP FILE\n",
    "    # =========================\n",
    "\n",
    "    zip_file = save_zip(fig1, fig2, fig3, fig4, fig5, fig6, fig7, fig8)\n",
    "\n",
    "    return total, avg_age, temp.head(20), fig1, fig2, fig3, fig4, fig5, fig6, fig7, fig8, zip_file\n",
    "\n",
    "# =========================\n",
    "# UI\n",
    "# =========================\n",
    "\n",
    "with gr.Blocks(theme=gr.themes.Soft()) as app:\n",
    "\n",
    "    gr.Markdown(\"# 🚦 CLEAN FIXED TRAFFIC DASHBOARD\")\n",
    "\n",
    "    with gr.Row():\n",
    "\n",
    "        with gr.Column(scale=1):\n",
    "            start_date = gr.Textbox(label=\"Start Date\")\n",
    "            end_date = gr.Textbox(label=\"End Date\")\n",
    "\n",
    "            category = gr.CheckboxGroup(choices=areas, label=\"Area\")\n",
    "\n",
    "            age_slider = gr.Slider(0, 100, value=50, label=\"Max Age\")\n",
    "\n",
    "            search = gr.Textbox(label=\"Search\")\n",
    "\n",
    "            btn = gr.Button(\"Apply\")\n",
    "\n",
    "            download = gr.File(label=\"Download Charts ZIP\")\n",
    "\n",
    "        with gr.Column(scale=3):\n",
    "\n",
    "            kpi1 = gr.Number(label=\"Total Records\")\n",
    "            kpi2 = gr.Number(label=\"Average Age\")\n",
    "\n",
    "            table = gr.Dataframe()\n",
    "\n",
    "            with gr.Row():\n",
    "                c1 = gr.Plot()\n",
    "                c2 = gr.Plot()\n",
    "                c3 = gr.Plot()\n",
    "                c4 = gr.Plot()\n",
    "\n",
    "            with gr.Row():\n",
    "                c5 = gr.Plot()\n",
    "                c6 = gr.Plot()\n",
    "                c7 = gr.Plot()\n",
    "                c8 = gr.Plot()\n",
    "\n",
    "    btn.click(\n",
    "        dashboard,\n",
    "        inputs=[start_date, end_date, category, age_slider, search],\n",
    "        outputs=[kpi1, kpi2, table, c1, c2, c3, c4, c5, c6, c7, c8, download]\n",
    "    )\n",
    "\n",
    "app.launch(share=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43b3a642-c1d2-4d74-bee5-27dc3ea833b6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
